// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC23n3vprSeZ9niLJX5OP_yiig8DjD4kiI',
    appId: '1:429018491525:web:db6bdaf278e165ff0817ec',
    messagingSenderId: '429018491525',
    projectId: 'lab8-033',
    authDomain: 'lab8-033.firebaseapp.com',
    storageBucket: 'lab8-033.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf5UntJmGbL-Vlr75UpGSxy8weNvbsCsE',
    appId: '1:429018491525:android:3f2a091027cecc0d0817ec',
    messagingSenderId: '429018491525',
    projectId: 'lab8-033',
    storageBucket: 'lab8-033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbzKLwG9ZEMoMg1RngSCxq-9PFTffQcA8',
    appId: '1:429018491525:ios:fa2dc7e71c06db140817ec',
    messagingSenderId: '429018491525',
    projectId: 'lab8-033',
    storageBucket: 'lab8-033.firebasestorage.app',
    iosClientId: '429018491525-hscltfsfehscnikesqp9v1hpdutdd73c.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8033',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbzKLwG9ZEMoMg1RngSCxq-9PFTffQcA8',
    appId: '1:429018491525:ios:fa2dc7e71c06db140817ec',
    messagingSenderId: '429018491525',
    projectId: 'lab8-033',
    storageBucket: 'lab8-033.firebasestorage.app',
    iosClientId: '429018491525-hscltfsfehscnikesqp9v1hpdutdd73c.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8033',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC23n3vprSeZ9niLJX5OP_yiig8DjD4kiI',
    appId: '1:429018491525:web:4f1f8378ecb2596f0817ec',
    messagingSenderId: '429018491525',
    projectId: 'lab8-033',
    authDomain: 'lab8-033.firebaseapp.com',
    storageBucket: 'lab8-033.firebasestorage.app',
  );
}
